# Use the official Python image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

COPY . .

# Install uv and dependencies
RUN pip install uv && \
    uv sync

# Default command for development
CMD ["uv", "run", "uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]